import os
import logging
import tempfile
from typing import Dict, Any, Optional, List
from pathlib import Path
from openai import AzureOpenAI
from dotenv import load_dotenv

load_dotenv()

class FileManager:
    """
    Manages file uploads and downloads for OpenAI Assistants.
    Handles CSV files and generated outputs.
    """
    
    def __init__(self):
        self.client = self._setup_azure_client()
        self.uploaded_files = {}  # session_id -> file_ids mapping
    
    def _setup_azure_client(self) -> AzureOpenAI:
        """Setup Azure OpenAI client"""
        return AzureOpenAI(
            api_key=os.getenv("AZUREAPI"),
            api_version=os.getenv("AZUREVERSION", "2024-05-01-preview"),
            azure_endpoint=os.getenv("AZUREENDPOINT")
        )
    
    def upload_csv_file(self, file_path: str, session_id: str) -> str:
        """
        Upload CSV file to OpenAI for assistant use.
        Returns file_id for attaching to messages.
        """
        try:
            with open(file_path, "rb") as file:
                uploaded_file = self.client.files.create(
                    file=file,
                    purpose="assistants"
                )
            
            file_id = uploaded_file.id
            
            # Store file mapping
            if session_id not in self.uploaded_files:
                self.uploaded_files[session_id] = []
            self.uploaded_files[session_id].append(file_id)
            
            logging.info(f"✅ Uploaded file {file_path} as {file_id} for session {session_id}")
            return file_id
            
        except Exception as e:
            logging.error(f"❌ Error uploading file {file_path}: {e}")
            raise
    
    def upload_csv_from_stream(self, file_stream, filename: str, session_id: str) -> str:
        """
        Upload CSV from stream (for web uploads) to OpenAI.
        Returns file_id for attaching to messages.
        """
        try:
            # Reset stream position
            file_stream.seek(0)
            
            # Create temporary file
            with tempfile.NamedTemporaryFile(delete=False, suffix=f"_{filename}") as temp_file:
                temp_file.write(file_stream.read())
                temp_path = temp_file.name
            
            try:
                # Upload to OpenAI
                with open(temp_path, "rb") as file:
                    uploaded_file = self.client.files.create(
                        file=file,
                        purpose="assistants"
                    )
                
                file_id = uploaded_file.id
                
                # Store file mapping
                if session_id not in self.uploaded_files:
                    self.uploaded_files[session_id] = []
                self.uploaded_files[session_id].append(file_id)
                
                logging.info(f"✅ Uploaded stream {filename} as {file_id} for session {session_id}")
                return file_id
                
            finally:
                # Clean up temp file
                try:
                    os.unlink(temp_path)
                except Exception as e:
                    logging.warning(f"⚠️ Could not delete temp file {temp_path}: {e}")
            
        except Exception as e:
            logging.error(f"❌ Error uploading stream {filename}: {e}")
            raise
    
    def download_generated_file(self, file_id: str, save_directory: str, 
                               filename: Optional[str] = None) -> str:
        """
        Download a file generated by the assistant.
        Returns the local file path.
        """
        try:
            # Get file content
            file_data = self.client.files.content(file_id)
            
            # Get file info for metadata
            file_info = self.client.files.retrieve(file_id)
            
            # Determine filename
            if not filename:
                filename = getattr(file_info, 'filename', f"generated_{file_id}")
                if '.' not in filename:
                    filename += ".png"  # Default to PNG for images
            
            # Ensure save directory exists
            os.makedirs(save_directory, exist_ok=True)
            
            # Save file
            save_path = os.path.join(save_directory, filename)
            with open(save_path, 'wb') as f:
                f.write(file_data.content)
            
            logging.info(f"📥 Downloaded file {file_id} to {save_path}")
            return save_path
            
        except Exception as e:
            logging.error(f"❌ Error downloading file {file_id}: {e}")
            raise
    
    def get_file_info(self, file_id: str) -> Dict[str, Any]:
        """Get information about an uploaded file"""
        try:
            file_info = self.client.files.retrieve(file_id)
            return {
                "id": file_info.id,
                "filename": getattr(file_info, 'filename', 'unknown'),
                "purpose": file_info.purpose,
                "status": file_info.status,
                "created_at": file_info.created_at,
                "bytes": file_info.bytes
            }
        except Exception as e:
            logging.error(f"❌ Error getting file info for {file_id}: {e}")
            return {}
    
    def list_session_files(self, session_id: str) -> List[str]:
        """Get list of file IDs for a session"""
        return self.uploaded_files.get(session_id, [])
    
    def delete_file(self, file_id: str) -> bool:
        """Delete a file from OpenAI"""
        try:
            self.client.files.delete(file_id)
            
            # Remove from our tracking
            for session_id, file_ids in self.uploaded_files.items():
                if file_id in file_ids:
                    file_ids.remove(file_id)
                    break
            
            logging.info(f"🗑️ Deleted file: {file_id}")
            return True
            
        except Exception as e:
            logging.error(f"❌ Error deleting file {file_id}: {e}")
            return False
    
    def cleanup_session_files(self, session_id: str) -> int:
        """Clean up all files for a session"""
        file_ids = self.uploaded_files.get(session_id, [])
        deleted_count = 0
        
        for file_id in file_ids:
            if self.delete_file(file_id):
                deleted_count += 1
        
        # Clear the session from our tracking
        if session_id in self.uploaded_files:
            del self.uploaded_files[session_id]
        
        logging.info(f"🧹 Cleaned up {deleted_count} files for session {session_id}")
        return deleted_count
    
    def get_file_content_as_string(self, file_id: str) -> str:
        """Get file content as string (for text files)"""
        try:
            file_data = self.client.files.content(file_id)
            return file_data.content.decode('utf-8')
        except Exception as e:
            logging.error(f"❌ Error getting file content for {file_id}: {e}")
            return ""